set -g prefix C-q
unbind C-b

# split window
unbind -
bind - split-window -v
unbind |
bind | split-window -h

# move to upper / right / down / left pane
unbind k
bind k select-pane -U
unbind l
bind l select-pane -R
unbind j
bind j select-pane -D
unbind h
bind h select-pane -L

# resize pane
unbind K
bind K resize-pane -U 8
unbind L
bind L resize-pane -R 8
unbind J
bind J resize-pane -D 8
unbind H
bind H resize-pane -L 8

# reload .tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# enable mouse
setw -g mouse on

set -g default-terminal "screen-256color"

# ステータスバーの色を設定する
set -g status-fg black
set -g status-bg colour214

# ペインボーダーの色を設定する
set -g pane-border-fg green
set -g pane-border-bg black

# アクティブペインを目立たせる
# set -g pane-active-border-fg white
# set -g pane-active-border-bg yellow

# 初期設定
splitw -d -t 1
resize-pane -t 1 -D 10
send-keys -t 1 emacsclient C-m
